// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from StartrekPlayer.djinni

package com.infteh.startrekplayer;

public enum StartrekMetadataSubscriptionType {
    CURRENT_SUBSCRIPTION,
    NEXT_SUBSCRIPTION,
    CURRENT_AND_NEXT_SUBSCRIPTION,
    ;
}
