// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from StartrekPlayer.djinni

package com.infteh.startrekplayer;

import java.util.ArrayList;

public abstract class StartrekMetadataWatcherDelegate {
    public abstract void connected();

    public abstract void disconnected();

    public abstract void metadata(String stationId, StartrekMetadata current, ArrayList<StartrekMetadata> next, ArrayList<StartrekMetadata> previous);
}
