// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from StartrekPlayer.djinni

package com.infteh.startrekplayer;

public enum StartrekPlayerQuality {
    AUTO_QUALITY,
    HIGH_QUALITY,
    MID_QUALITY,
    LOW_QUALITY,
    ;
}
