// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from StartrekPlayer.djinni

package com.infteh.startrekplayer;

public enum StartrekMetadataFetchType {
    FULL_FETCH,
    CURRENT_FETCH,
    ;
}
