// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from StartrekPlayer.djinni

package com.infteh.startrekplayer;

import java.util.ArrayList;

public abstract class StartrekPlayerDelegate {
    public abstract void ended();

    public abstract void error(String message);

    public abstract void streamUrlChanged(String streamUrl);

    public abstract void isRestartedChanged(boolean isRestarted);

    public abstract void isHlsChanged(boolean isHls);

    public abstract void isSeekableChanged(boolean isSeekable);

    public abstract void stateChanged(StartrekPlayerState state);

    public abstract void isPlayingChanged(boolean isPlaying);

    public abstract void isStalledChanged(boolean isStalled);

    public abstract void isPausedChanged(boolean isPaused);

    public abstract void isStoppedChanged(boolean isStopped);

    public abstract void lengthChanged(double length);

    public abstract void bufferedLengthChanged(double bufferedLength);

    public abstract void startPositionChanged(double startPosition);

    public abstract void positionChanged(double position);

    public abstract void playbackRateChanged(double playbackRate);

    public abstract void metaChanged(String meta);

    public abstract void volumeChanged(double volume);

    public abstract void duckVolumeChanged(boolean duckVolume);

    public abstract void playingBitratesChanged(ArrayList<Integer> playingBitrates);

    public abstract void availableBitratesChanged(ArrayList<Integer> availableBitrates);

    public abstract void currentBitrateChanged(int currentBitrate);

    public abstract void currentQualityChanged(StartrekPlayerQuality currentQuality);

    public abstract void playingBitrateChanged(int playingBitrate);

    public abstract void playingQualityChanged(StartrekPlayerQuality playingQuality);

    public abstract void daastUrlChanged(String daastUrl);

    public abstract void daastStarted(String meta, String imageUrl, String clickUrl);

    public abstract void daastError(String message);

    public abstract void daastSkipped();

    public abstract void daastEnded();
}
