// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from StartrekPlayer.djinni

package com.infteh.startrekplayer;

public enum StartrekPlayerState {
    PLAYING_STATE,
    STALLED_STATE,
    PAUSED_STATE,
    STOPPED_STATE,
    ERROR_STATE,
    ;
}
