// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from StartrekPlayer.djinni

package com.infteh.startrekplayer;

public abstract class StartrekMetadataUpdaterDelegate {
    public abstract void metaUrlChanged(String metaUrl);

    public abstract void metaIdUrlChanged(String metaIdUrl);

    public abstract void titleChanged(String title);

    public abstract void subtitleChanged(String subtitle);

    public abstract void coverUrlChanged(String coverUrl);

    public abstract void ddbIdChanged(int ddbId);

    public abstract void typeChanged(int type);
}
